version: '3.8'

services:
   app:
      image: nestjs-docker:local
      container_name: nestjs-docker
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 3000:3000
      volumes:
         - .:/app
